### ISSUE TITLE
Incorrect bytes order (chunks) in uploaded file. 

### ISSUE THREAD

**Issue by lomoval** [ardatan/schema-stitching#180]
I have a problem with uploading files through the gateway.
Small files work fine. But if the file is split into chunks during transmission, then the resulting file has the wrong order of chunks.
This problem occurred when I was checking the Yoga server and stitching with my Go server (gqlgen). 
Resulting zip files were broken.
I have recheck your example https://github.com/ardatan/schema-stitching/tree/master/examples/graphql-upload and got the same result.

**Steps to reproduce:**
1. Create a file with content 
```
1
2
3
4
5
...
10000
```
2. Start services from here  https://github.com/ardatan/schema-stitching/tree/master/examples/graphql-upload
3. Upload file from step 1 to gateway with upload mutation `mutation add($file: File!){  uploadFile(file:$file){ name } }`

**Expected behavior**:
Uploaded(stored) file has same content as source file.

**Actual behavior**:
Content of uploaded(stored) file is different from source file. I have attached the source file and the saved file from my check as an example.
![dif](https://github.com/ardatan/schema-stitching/assets/64064940/1012c796-9d71-4294-abd2-5fdddc737f51)
Source: [checkFile.txt](https://github.com/ardatan/schema-stitching/files/12451249/checkFile.txt)
Uploaded: [checkFile.txt](https://github.com/ardatan/schema-stitching/files/12451254/checkFile.txt)

**Additional info**
OS Name: Microsoft Windows 10 Home Single Language
OS Version: 10.0.19045 N/A Build 19045
Node Version: v20.5.1
Yarn Version: 1.22.11

**Comment by ardatan** [comment]
Would you create a PR with a failing test here?
https://github.com/ardatan/schema-stitching/tree/master/examples/graphql-upload/tests

**Comment by ardatan** [comment]
Fixed in the latest versions! Thanks for the feedback!
